[package]
name = "geopard"
version = "0.1.0"
authors = ["ranfdev <ranfdev@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
version = "0.9.0"
features = ["v3_24"]

[dependencies.glib]
version = "0.10.0"
features = ["v2_60"]

[dependencies.gio]
version = "0.9.0"

[dependencies.gdk]
version = "0.13.0"

[dependencies.async-tls]
version = "0.9.0"
default-features = false
features = ["client"]

[dependencies]
async-std = {version = "1.6.2", features = ["unstable", "attributes"]}
url = "2.1.1"
thiserror = "1.0.20"
bytes = "0.5.6"
futures = "0.3.5"
regex = "1.3.9"
once_cell = "1.4.0"
anyhow = "1.0.32"
async-trait = "0.1.38"
async-native-tls = "0.3.3"
