name: "Build flatpak"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: sudo apt install flatpak-builder flatpak jq
    - run: bash ./build-aux/build-flatpak.sh build ./build-aux/com.ranfdev.Geopard.json

